# The URL the site will be built for
base_url = "https://resorie.github.io/blog"

title = "Runtime Error"
description = "Resory's blog"

theme = "nivis"

generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

compile_sass = true

taxonomies = [{ name = "tags", paginate_by = 5 }]

[markdown]
render_emoji = true
github_alerts = true
bottom_footnotes = true

[markdown.highlighting]
style = "class"
light_theme = "one-light"
dark_theme = "one-dark-pro"
extra_grammars = [ "themes/nivis/syntaxes/math-display.json" ]

[extra]
main_section = "posts"
avatar = "images/avatar.jpeg"

math_display = "mathjax"

# Social links
social_links = [
    { name = "github", url = "https://github.com/resorie" },
    { name = "email", url = "mailto:resorie@qq.com" },
    { name = "bilibili", url = "https://space.bilibili.com/399133773" },
]
